List <Map> videos = [
  {
    "title": "Guns N' Roses - Paradise City (Official Music Video)",
    "thumbnail": "https://i.ytimg.com/vi/Rbm6GXllBiw/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvwaXBObKx-7Z4o74-Sx2muQUcNQ",
    "length": "6:49",
    "name": "Guns N' Roses",
    "views": "745M views",
    "date": "12 years ago",
    "profile": "https://yt3.googleusercontent.com/XYdITfFzeQBLoNsIIpthkC1jfK9r-jVijx_ULuralq1KaN35Z_tJdgyoB9O-eSCm_NdEgN1E-Ok=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    "title": "Avatar: The Way of Water | Official Trailer",
    "thumbnail": "https://i.ytimg.com/vi/d9MyW72ELq0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCRTfyihvnh7UWO5qpp_hgtIdkCow",
    "length": "2:28",
    "name": "Avatar",
    "views": "41M views",
    "date": "1 month ago",
    "profile": "https://yt3.ggpht.com/ytc/AMLnZu-qPHlOU8j2gApNMNDn0NPBxTZyrDovuamHV3jh_Q=s88-c-k-c0x00ffffff-no-rj",
  },
  {
    "title": "100 Girls Vs 100 Boys For \$500,000",
    "thumbnail": "https://i.ytimg.com/vi/tVWWp1PqDus/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDtQwKuTHfgVKGNquw9hV_A74EZ7A",
    "length": "16:53",
    "name": "MrBeast",
    "views": "103M views",
    "date": "4 month ago",
    "profile": "https://yt3.googleusercontent.com/ytc/AMLnZu9ouu2eBFlCyh6lORj8YUCdNENJRst9IoU5sYf1Ig=s176-c-k-c0x00ffffff-no-rj",
  },
  {
    "title": "Emotional & Heartbreaking Moments in Football",
    "thumbnail": "https://i.ytimg.com/vi/9AMQBwG3smY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAQAFD-hXa7aHR0xxXvhGRxND8ohg",
    "length": "8:57",
    "name": "SEN31 Extra",
    "views": "40K views",
    "date": "9 hours ago",
    "profile": "https://yt3.ggpht.com/Ar2FsWptR_3Sq0gi3299Bci5Y_0HWy7L99nPBkVUUFD94DTAK1_pNoMpan3Av4UeyS9ZrVTOrhw=s88-c-k-c0x00ffffff-no-rj",
  },
  {
    "title": "Lionel Messi - The GOAT - Official Movie",
    "thumbnail": "https://i.ytimg.com/vi/G4wTERfoPfA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCeMFB7cUTuSf_4eDs0vrgA2NvKVg",
    "length": "19:59",
    "name": "MagicalMessi",
    "views": "27M views",
    "date": "3 years ago",
    "profile": "https://yt3.ggpht.com/ytc/AMLnZu_LvAcnwZs9GyUToiN1S2P4ciFd_fMrbmHKB0wV6A=s176-c-k-c0x00ffffff-no-rj",
  },
];